MailKit/MailService.cs
Method Connect fail with ArgumentOutOfRangeException ("port")
if uri do not contains port declaration
simple test case below that works in mailkit v1.0.2 but broken in v1.0.13 
using(var client = new ImapClient()) {
client.Connect(new Uri("imap://box.example.com"));
}
=> Fix MailService.Connect method

MailKit/Net/Imap/ImapUtils.cs
This fixes an issue with parsing things from IMAP servers that don't surround folder names in quotes and start them with weird characters like "[" that the tokenizer normally takes apart. This is similar to the issue #193
=> Fixed issue with parsing unescaped folder names.

MailKit/Net/Imap/ImapFolder.cs
Remove alternate code paths for always-false or always-true code according to static analysis.
=> Remove alternate code paths for always-false or always-true code

MailKit/ProtocolLogger.cs
The existing constructor for directing ProtocolLogger to a file, opened the file with an exclusive lock. This prevents even read access to the file while open by MailKit, and hence prevents Tailing the file while performing operations. 
Modified the constructor to open the file in a shared read mode.
Also added an option to Append or Overwrite the file. The existing behavior is a bit odd, with File.OpenWrite causing the file to be overwritten from the beginning, but not truncated. The new behavior defaults to Append.
=> Modified ProtocolLogger log-to-file constructor to support Shared Read and append/overwrite option

MailKit/Net/Smtp/SmtpClient.cs
When sending email with multiple recipients and one or more recipient addresses are not accepted by server the whole email is aborted. In my case it was email with lots of BCC recipients where one of them had invalid email address, the whole email was not delivered.
This PR adds the `SmtpStatusCode.SyntaxError` case to `ProcessRcptToResponse` and allows the `OnRecipientNotAccepted` to handle the error.
=> Allow handling smtp status code SyntaxError for invalid recipient addresses.

MailKit/Net/Imap/AsyncImapClient.cs, MailKit/Net/Imap/ImapClient.cs, UnitTests/Net/Imap/ImapClientTests.cs
Added ImapClient.Connect() overload which accepts a Stream instead of a Socket
This is useful for running an IMAP server (e.g. dovecot) locally and simply passing a Stream connected to the server's stdin/stdout to ImapClient. (Most IMAP server can be run in a mode where the Stream is immediately authenticated and the server's stdin/stdout form an IMAP connect.)
=> Added ImapClient.Connect() overload which accepts a Stream instead of a Socket

MailKit/Net/Imap/ImapFolderSearch.cs
always register the untagged SEARCH handler because some servers will brokenly respond with "* SEARCH ..." instead of "* ESEARCH ..." even when using the extended search syntax.
In order to address iCloud responding with * SEARCH:
```
C: E00000007 UID SEARCH RETURN () SENTSINCE 27-May-2019
S: * SEARCH 3
S: E00000007 OK SEARCH completed (took 51 ms)
```
=> Add SearchMatchesHandler

Documentation/Examples/ImapIdleExample.cs
readonly SecureSocketOptions options was not used, whilst constructor was referring to a non existing Ssloptions.
I believe you would want these to reference eachother.
=> Fixed ImapIdle example code

MailKit/Net/Proxy/HttpProxyClient.cs
Hello, thanks for your awesome library! However, I've encountered a strange behaviour, which occurs when I use specific http proxies for connecting to IMAP server:
```
MailKit.Net.Proxy.ProxyProtocolException: Failed to connect to imap.rambler.ru:993: HTTP/1.1 200 OK
at MailKit.Net.Proxy.HttpProxyClient.ConnectAsync(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.Proxy.ProxyClient.ConnectAsync(String host, Int32 port, Int32 timeout, CancellationToken cancellationToken)
at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
```
The …
=> Consider 200 OK with empty body as a successful connection

MailKit/Net/Proxy/Socks5Client.cs
MailKit sends an invalid authentication request, which leads to disconnection from proxy server.
Due to [RFC1929](https://tools.ietf.org/html/rfc1929), during authentication `VER` field should always equal to `1`:
> The VER field contains the current version of the subnegotiation, which is X'01'.
However, Socks5Client sends a protocol version, which is `5`.
=> Fix protocol violation in SOCKS5 authentication procedure

MailKit/IMailSpool.cs
For some reason GetMessageCountAsync was not part of the IMailSpool interface, so I added it.
=> Added GetMessageSizeAsync to IMailSpool

MailKit/Net/Imap/ImapUtils.cs
Avoid unnecessary string copies and use efficient EqualsIgnoreCaseAsciiHelper method 
https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/mscorlib/system/string.cs#L625
=> Avoid unnecessary string copies.

FAQ.md
Fix typo in `HasFlags` method call in `SmtpClient` example (capital `L` instead of correct lowercase `l`)
=> Fix typo in `HasFLags` in FAQ.md

ExchangeOAuth2.md
Fixed a typo in `ExchangeOAuth2.md` (from `inforrmation` to `information`).
=> Fixed typo in ExchangeOAuth2.md

MailKit/ByteArrayBuilder.cs, MailKit/MailKit.csproj, MailKit/MailKitLite.csproj, MailKit/Net/Imap/HashCode.cs, MailKit/Net/Imap/ImapToken.cs, MailKit/Net/Imap/ImapTokenCache.cs
Unfortunately, it seems not to really help much since the vast majority of tokens are either QStrings (not cached) or numeric tokens (also not cached since it wouldn't make sense).
I could look into caching qstring tokens as well, but it gets more complicated if they aren't us-ascii.
Also might be worth adding the ImapTokenType to the hash code calculation... right now it's not needed because we only cache atom and flag tokens (which won't collide). QString tokens might since the tokens would be unquoted.
=> Added an ImapToken cache to try and reduce ImapToken allocations

README.md
As a new user of this library, looking into the Readme and docs for the first time, I struggled to find the amazing(!) complete examples provided in the documentation.
IMHO thus giving a short link there, that there are more examples, is very helpful!
=> doc: add link to examples

samples/ImapIdle/ImapIdle/IdleClient.cs
IMHO this is way easier to read.
=> Use TimeSpan.FromMinute instead of TimeSpan constructor increasing readability

MailKit/Net/Imap/ImapUtils.cs, UnitTests/Net/Imap/ImapUtilsTests.cs
First of all, thank you very much for your work on MailKit. I'm very pleased to have the opportunity to contribute to it !
Now, let's see what I found 😃.
The `FormatInternalDate` method has a bug when handling time zones with negative offsets where the minutes component was non-zero. This resulted in incorrectly formatted outputs. Specifically, the method produced an invalid format with an extra negative sign for the minutes part. Examples of the incorrect outputs included:
```
Expected: 14-May-2023 12:30:45 -0430
But was: 14-May-2023 12:30:45 -04-30
Expected: 15-May-2023 12:30:45 -0330
But was: 15-May-2023 12:30:45 -03-30
```
These incorrect outputs are associated with time zones such as:
- Venezuela Standard Time (VET), which is UTC-04:30.
- Newfoundland Standard Time (NST), which is …
=> FormatInternalDate outputs wrong formatted dates with timezones having negative offsets

MailKit/Net/Imap/ImapFolder.cs
ArgumentException is apparently not only thrown when the `name` is empty, but also when the server rejects it, because it e.g. has a directory separator char in it.
See https://stackoverflow.com/questions/78844815/how-to-create-or-get-folders-in-mailkit-with-multiple-sub-folders-when-they-ar/78844857#78844857 for details.
=> Adjust ImapFolder.Create(Async) to document ArgumentException fully

FAQ.md
IMHO, many people using this lib may use it to automatically send replies. Sure, some may have some human in the loop, but we can assume that.
As such, IMHO; the FAQ should point that out.
Related to https://github.com/jstedfast/MimeKit/issues/938 of course and there are plenty of more headers to set in such a case, but it feels like this was the most standardized one and in any case the minimal one to do?
Also, the FAQ entry is about replying, so the header value does exactly reflect that. If you want to suppress responses or so, that may be an additional requirement.
I just want to minimize the amount of systems not following the spec and ignoring such an important thing. 🙃
=> docs: clarify/add the recommendation to set AutoSubmitted if needed

MailKit/MailKit.csproj, MailKit/Net/IChannelBindingContext.cs, MailKit/Net/Smtp/SmtpClient.cs, MailKit/Net/SslStream.cs, MailKit/Security/SaslMechanism.cs, MailKit/Security/SaslMechanismGssapi.cs, UnitTests/Security/ChannelBindingContext.cs
- new `GssapiSaslMechanism` class which uses `NegotiateAuthentication` class
- fixed `SmtpClient` for after auhentication handshake
- add `GetChannelBinding` into `IChannelBindingContext`
- create `GSSAPI_FEATURE` define for more readable and maintainable GSSAPI conditional compiling
- wiring GSSAPI up
Kerberos is somehow difficult to test, however I did my best to validate those changes. I have created two VMs in my local HyperV. One domain controler plus exchange server. Second windows client which runts tested code in following scenarios:
- non SSL GSSAPI
- SSL GSSAPI
- SSL + channel binding GSSAPI
Works for both `Authenticate(ICredentials)` and `Authernticate(SaslMechanism)`
=> GSSAPI implementation
